### ISSUE TITLE
Dependency no longer exists

### ISSUE THREAD

**Issue by bilogic** [sitelease/sugar-cube-client#2]
https://github.com/cedx/enum.php has either been made private or doesn't exists. Can fix?

**Comment by tahaghafuri** [comment]
Fixed Here https://github.com/tahaghafuri/sugar-cube-client

**Comment by bilogic** [comment]
Thanks! I also fixed it myself some time back.

**Comment by mooror** [comment]
Finally got around to fixing this issue
